import React from 'react';

export default function Reports({ user }) {
  const goals = user?.goals || [];
  const now = new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' });
  const totalTopics = goals.reduce((s,g) => s+(g.topics?.length||0), 0);
  const doneTopics = goals.flatMap(g=>g.topics||[]).filter(t=>['COMPETENT','PROFICIENT','MASTERED'].includes(t.mastery)).length;

  const report = `LearnOS — Learning Report
Generated: ${now}
Learner: ${user?.name || 'Unknown'}
Type: ${user?.learnerType || 'N/A'}
Daily Target: ${user?.dailyTarget || 0}h

═══════════════════════════════════
SUMMARY
═══════════════════════════════════
Active Goals:       ${goals.length}
Total Topics:       ${totalTopics}
Topics Progressing: ${doneTopics}
Topics Remaining:   ${totalTopics - doneTopics}

═══════════════════════════════════
GOALS
═══════════════════════════════════
${goals.length === 0 ? 'No goals added yet.' : goals.map(g => `
▸ ${g.title} [${g.category}]
  Why: ${g.why}
  Target: ${g.targetMastery}${g.deadline ? `  |  Deadline: ${g.deadline}` : ''}
  Topics:
${(g.topics||[]).map(t => `    • ${t.name.padEnd(20)} ${t.mastery}`).join('\n') || '    No topics added'}
`).join('\n')}

═══════════════════════════════════
Generated by LearnOS · Personal Learning Intelligence
`;

  const handleExport = () => {
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LearnOS-Report-${now}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fade-up">
      <div className="page-header" style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start' }}>
        <div>
          <h1 className="page-greeting">Learning <em>Report</em></h1>
          <p className="page-subtitle">Generated {now}</p>
        </div>
        <button className="btn btn-primary" onClick={handleExport}>↓ Export .txt</button>
      </div>

      <div className="grid-4" style={{ marginBottom:24 }}>
        {[
          { v: goals.length, l: 'Active Goals', c: 'var(--navy)' },
          { v: totalTopics, l: 'Total Topics', c: 'var(--lavender)' },
          { v: doneTopics, l: 'Progressing', c: 'var(--sage)' },
          { v: totalTopics - doneTopics, l: 'Remaining', c: 'var(--rose)' },
        ].map(item => (
          <div key={item.l} className="card fade-up" style={{ textAlign:'center' }}>
            <div style={{ fontFamily:'var(--font-display)', fontSize:40, color:item.c }}>{item.v}</div>
            <div style={{ fontSize:11, color:'var(--text-muted)', textTransform:'uppercase', letterSpacing:'0.8px', marginTop:4 }}>{item.l}</div>
          </div>
        ))}
      </div>

      <div className="card fade-up">
        <div className="section-title">Full Report Preview</div>
        <pre style={{ fontFamily:'"Courier New", monospace', fontSize:13, color:'var(--text-primary)', lineHeight:1.7, whiteSpace:'pre-wrap', background:'var(--cream-dark)', padding:24, borderRadius:'var(--radius-sm)', overflowX:'auto' }}>
          {report}
        </pre>
      </div>
    </div>
  );
}
