import React from 'react';
import { mockGoals, mockLEI, mockUser, mockInsights } from '../api/data';

export default function Reports() {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const riskClass = mockLEI.score >= 75 ? 'low' : mockLEI.score >= 50 ? 'medium' : 'high';

  const reportText = `
LearnOS — Learning Efficiency Report
Generated: ${now}
Student: ${mockUser.name}

═══════════════════════════════════════
LEARNING EFFICIENCY INDEX: ${mockLEI.score}/100
Risk Level: ${riskClass.toUpperCase()}
═══════════════════════════════════════

AGENT SCORES
────────────────────────────────────────
Productivity:       ${mockLEI.productivity}/100
Mastery Velocity:   ${mockLEI.mastery}/100
Retention:          ${mockLEI.retention}/100
Topic Priority:     ${mockLEI.topicPriority}/100
Deadline:           ${mockLEI.deadline}/100
Goal Progress:      ${mockLEI.goalProgress}/100
Cognitive Load:     ${mockLEI.cognitive}/100
Motivation:         ${mockLEI.motivation}/100

GOAL PROGRESS
────────────────────────────────────────
${mockGoals.map(g => `${g.title} [${g.category}]: ${g.progress}%
  Topics: ${g.topics.map(t => `${t.name} (${t.mastery})`).join(', ')}`).join('\n\n')}

ACTIVE INSIGHTS
────────────────────────────────────────
${mockInsights.map((ins, i) => `${i + 1}. [${ins.type}] ${ins.message}`).join('\n\n')}

LEI Formula:
  (Mastery Velocity × 0.30) + (Topic Coverage × 0.25) +
  (Retention × 0.20) + (Consistency × 0.15) +
  (Goal Progress × 0.10) − Cognitive Penalty

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by LearnOS — Personal Learning Intelligence
`;

  const handleExport = () => {
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LearnOS-Report-${now}.txt`;
    a.click();
  };

  return (
    <div className="fade-up">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h1 className="page-greeting">Learning <em>Report</em></h1>
          <p className="page-subtitle">Generated {now}</p>
        </div>
        <button className="btn btn-primary" onClick={handleExport}>
          ↓ Export .txt
        </button>
      </div>

      {/* Summary Cards */}
      <div className="grid-4" style={{ marginBottom: 24 }}>
        <div className="card fade-up" style={{ textAlign: 'center' }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 40, color: mockLEI.score >= 75 ? 'var(--sage)' : mockLEI.score >= 50 ? 'var(--yellow)' : 'var(--rose)' }}>{mockLEI.score}</div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.8px', marginTop: 4 }}>LEI Score</div>
        </div>
        <div className="card fade-up" style={{ textAlign: 'center' }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 40, color: 'var(--navy)' }}>{mockGoals.length}</div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.8px', marginTop: 4 }}>Active Goals</div>
        </div>
        <div className="card fade-up" style={{ textAlign: 'center' }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 40, color: 'var(--lavender)' }}>
            {mockGoals.flatMap(g => g.topics).filter(t => ['COMPETENT','PROFICIENT','MASTERED'].includes(t.mastery)).length}
          </div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.8px', marginTop: 4 }}>Topics Progressing</div>
        </div>
        <div className="card fade-up" style={{ textAlign: 'center' }}>
          <div style={{ fontFamily: 'var(--font-display)', fontSize: 40, color: 'var(--rose)' }}>{mockInsights.filter(i => i.severity === 'urgent').length}</div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.8px', marginTop: 4 }}>Urgent Alerts</div>
        </div>
      </div>

      {/* Full Report Text */}
      <div className="card fade-up">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
          <div className="section-title" style={{ margin: 0 }}>Full Report</div>
        </div>
        <pre style={{
          fontFamily: '"Courier New", monospace',
          fontSize: 13,
          color: 'var(--text-primary)',
          lineHeight: 1.7,
          whiteSpace: 'pre-wrap',
          background: 'var(--cream-dark)',
          padding: 24,
          borderRadius: 'var(--radius-sm)',
          overflowX: 'auto',
        }}>
          {reportText}
        </pre>
      </div>
    </div>
  );
}
